### ISSUE TITLE
OMERO 5.2

### ISSUE THREAD

**Issue by GHAStVHenry** [ome/omero-mapr#53]
Howdy, we only have OMERO 5.2 installed on our server... is there any stable version of mapr which is compatible with it?

**Comment by manics** [comment]
Hi, I'm afraid OMERO 5.2 isn't supported by Mapr. It's a relatively new application and has had a lot of development, so OMERO 5.4 or later is required.

Note OMERO 5.2 is unsupported and contains some security vulnerabilities that have been fixed in later versions: https://www.openmicroscopy.org/security/advisories/ so we'd strongly advise you to upgrade.

**Comment by GHAStVHenry** [comment]
Thanks for the info... I'll get on my HPC to try and get the upgrade...
